[project]
name = "pybsp"
version = "0.1.0"
description = "Support code for analysing BSP data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "scienceplots>=2.2.2",
    "seaborn>=0.13.2",
    "typer>=0.27.2",
]

[project.scripts]
bsp-grid = "pybsp.cli:grid_app"
bsp-plot = "pybsp.cli:plot_app"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["python"]
include = ["pybsp*"]
